name: Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install -f

      - run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Archive test reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: karma_testReports
          path: test-results/

  deploy:
    needs: build
    runs-on: windows-latest
    if: success()  # Deploy only when the build is successful
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Deployment Files
        run: |
          mkdir deploy
          cp -R test-results deploy/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy  # The folder you want to deploy as the GitHub Pages site

      - name: Display GitHub Pages Link
        run: |
          echo "GitHub Pages link:"
          echo "https://sayyed-muzammil04.github.io/Demo/"
