# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -f
    - run: npm test -- --watch=false --browsers=ChromeHeadless
    
    - name: Archive test reports
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: karma_testReports
        path: test-results/

    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      if: success() || failure()
      with:
        branch: main  
        folder: test-results  
       
    - name: Display GitHub Pages Link
      if: success() || failure()
      run: |
        echo "GitHub Pages link:"
        echo "https://sayyed-muzammil04.github.io/Demo/"
       
    - name: Finalize
      if: always()
      run: echo "Artifacts generated and uploaded"
